# import glob for iterating files in folder and use dataframe for structuring

In [1]:
import glob
import pandas as pd

body=[]
list_of_files = glob.glob('/Users/ajinkya.parkar@ibm.com/Documents/deep/spam_data/0*.txt')

for fileName in list_of_files:
    
    file = open(fileName, encoding = "ISO-8859-1")
    body.append(file.read())
    
    file.close()

body_file = pd.DataFrame(data = body,columns = ['post'])




# extract label file

In [2]:
#list_of_labels = glob.glob('/Users/ajinkya.parkar@ibm.com/Documents/deep/spam_data/labels.txt')
label_file = pd.read_csv('/Users/ajinkya.parkar@ibm.com/Documents/deep/spam_data/labels.txt',header = None,delimiter=" ",names=["label",'Name'])



In [3]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

In [4]:
import itertools
import os

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn.preprocessing import LabelBinarizer, LabelEncoder
from sklearn.metrics import confusion_matrix

from tensorflow.contrib.keras.python import keras
from tensorflow.contrib.keras.python.keras.models import Sequential
from tensorflow.contrib.keras.python.keras.layers import Dense, Activation, Dropout
from tensorflow.contrib.keras.python.keras.preprocessing import text, sequence
from tensorflow.contrib.keras.python.keras import utils

# This code was tested with TensorFlow v1.3
print("You have TensorFlow version", tf.__version__)

You have TensorFlow version 1.3.0


# Set index for train and test

In [5]:
# Split data into train and test
train_size = int(len(body_file) * .5)
print ("Train size: %d" % train_size)
print ("Test size: %d" % (len(body_file) - train_size))

Train size: 25
Test size: 25


# Prepare train and test data in 50:50 ratio

In [46]:

train_posts = body_file['post'][:train_size]
train_tags = label_file['label'][:train_size]

test_posts = body_file['post'][train_size:]
test_tags = label_file['label'][train_size:]


0     One of a kind Money maker! Try it for free!Fro...
1     link to my webcam you wanted Wanna see sexuall...
2     Re: How to manage multiple Internet connection...
3     [SPAM]  Give her 3 hour rodeoEnhance your desi...
4     Best Price on the netf5f8m1 (suddenlysusan@Sto...
5     linux.ie mailing list memberships reminderThis...
6     Re: Apple Sauced...againAt 1:16 AM -0400 on 10...
7     Re: results for giant mass-check (phew)I never...
8     Re: RPM's %post, %postun etcHave you tried reb...
9     Re: Fwd: Re: Kde 3.5 ...On 9 May 2010 17:00, L...
10    Re: (no subject)I've picked up these patches a...
11    Enter now, hibody, 75% off<!DOCTYPE html PUBLI...
12    [use Perl] Stories for 2002-08-31use Perl Dail...
13    [SPAM]  Summer timeFrom nobody Mon Sep 18 18:0...
14    Crystal Clear Conference Calls<HTML><HEAD><TIT...
15    Get Your Own Great-Looking WebsiteThis is a mu...
16    Re: [ILUG] cheap linux PCs>I'd normally never ...
17    Re[2]: Selling Wedded Bliss (was Re: Ouch.

File 1) a bunch of text
Label 1) spam

File 2) a bunch more text
Label 2) not spam


more text

x_train 1) 0, 1
x_train 2) 1, 1

testing example 1) more text
x_test 1) 1, 1





In [7]:
len(train_posts), len(train_tags)

(25, 25)

In [8]:
len(test_posts), len(test_tags)

(25, 25)

# Set bag of words array length

In [9]:
max_words = 100
tokenize = text.Tokenizer(num_words=max_words, char_level=False)

# train posts

In [10]:
tokenize.fit_on_texts(train_posts) # only fit on train

In [28]:
text = "tr"
# tokenize the text, and retrieve the index of the first 10 tokens
tokenize.texts_to_matrix([text])


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [31]:
x_train = tokenize.texts_to_matrix(train_posts)
x_test = tokenize.texts_to_matrix(test_posts)


In [39]:
#print(tokenize.word_index)
x_train[0]

array([ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  0.,
        1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,
        1.,  0.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,  1.,
        1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  1.,
        0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,
        0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.])

In [44]:
encoder = LabelEncoder()
encoder.fit(train_tags)
y_train = encoder.transform(train_tags)
y_test = encoder.transform(test_tags)


array([1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1])

In [45]:
num_classes = np.max(y_train) + 1
y_train = utils.to_categorical(y_train, num_classes)
y_test = utils.to_categorical(y_test, num_classes)


array([[ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  0.],
       [ 1.,  0.],
       [ 0.,  1.],
       [ 1.,  0.]])

In [17]:
print('x_train shape:', x_train.shape)
print('x_test shape:', x_test.shape)
print('y_train shape:', y_train.shape)
print('y_test shape:', y_test.shape)
num_classes

x_train shape: (25, 100)
x_test shape: (25, 100)
y_train shape: (25, 2)
y_test shape: (25, 2)


2

In [18]:
batch_size = 5
epochs = 10

In [19]:
model = Sequential()
model.add(Dense(512, input_shape=(max_words,)))
model.add(Activation('relu'))
model.add(Dense(num_classes))
model.add(Activation('softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])



In [20]:
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_split=0.1)

Train on 22 samples, validate on 3 samples
Epoch 1/10
22/22 [==============================] - 0s - loss: 0.5975 - acc: 0.7273 - val_loss: 0.3789 - val_acc: 1.0000
Epoch 2/10
22/22 [==============================] - 0s - loss: 0.3367 - acc: 0.9091 - val_loss: 0.3237 - val_acc: 0.6667
Epoch 3/10
22/22 [==============================] - 0s - loss: 0.2370 - acc: 0.9091 - val_loss: 0.2910 - val_acc: 0.6667
Epoch 4/10
22/22 [==============================] - 0s - loss: 0.1663 - acc: 1.0000 - val_loss: 0.2908 - val_acc: 0.6667
Epoch 5/10
22/22 [==============================] - 0s - loss: 0.1222 - acc: 1.0000 - val_loss: 0.3118 - val_acc: 0.6667
Epoch 6/10
22/22 [==============================] - 0s - loss: 0.0892 - acc: 1.0000 - val_loss: 0.3181 - val_acc: 0.6667
Epoch 7/10
22/22 [==============================] - 0s - loss: 0.0665 - acc: 1.0000 - val_loss: 0.3367 - val_acc: 0.6667
Epoch 8/10
22/22 [==============================] - 0s - loss: 0.0524 - acc: 1.0000 - val_loss: 0.3564 - val_a

In [21]:
score = model.evaluate(x_test, y_test,
                       batch_size=batch_size, verbose=1)
print('Test score:', score[0])
print('Test accuracy:', score[1])

 5/25 [=====>........................] - ETA: 0sTest score: 0.604663082957
Test accuracy: 0.800000011921


In [22]:
from scipy.spatial import distance
def eucledean(a,b):
        return distance.euclidean(a,b)

In [23]:
class myCustomClassifier():
    
    
    def fit(self,x_train,y_train):
        self.x_train = x_train
        self.y_train = y_train
        
    def closest(self,row):
        closest_distance = eucledean(row,self.x_train[0])
        closest_index = 0
        for i in range(1,len(x_train)):
            
            dist = eucledean(row,self.x_train[i])
            if dist < closest_distance:
                closest_distance = dist
                closest_index = i
                
        return self.y_train[closest_index]
        
    def predict(self,x_test):
        predictions = []
        for row in x_test:
            #print(row)
            label = self.closest(row)
            predictions.append(label)
        return predictions

In [24]:
knn = myCustomClassifier()
knn.fit(x_train, y_train) 

In [25]:
Final_predictions = knn.predict(x_test)
print(len(Final_predictions))
print(Final_predictions)

[ 0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  1.  0.  1.  0.  0.  0.  1.
  1.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  1.  0.  1.  1.  0.  0.  0.
  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  1.  0.  1.  0.  1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  1.  1.  0.  1.  1.  0.  0.  1.
  1.  0.  1.  1.  1.  1.  0.  0.  1.  0.  1.  0.  0.  1.  1.  1.  0.  0.
  0.  1.  0.  1.  0.  0.  1.  0.  0.  0.  0.  1.  0.  1.  0.  0.  1.  0.
  0.  0.  1.  1.  0.  1.  1.  0.  1.  0.  1.  1.  1.  1.  0.  1.  0.  1.
  1.  1.  0.  0.  1.  1.  0.  0.  1.  1.  0.  0.  0.  0.  1.  1.  1.  1.
  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.]
[ 0.  0.  0.  1.  0.  0.  1.  1.  0.  0.  0.  0.  0.  1.  0.  0.  1.  1.
  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.

[ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  0.
  0.  1.  1.  1.  0.  1.  1.  0.  1.  1.  0.  1.  1.  1.  1.  0.  1.  1.
  1.  1.  0.  1.  1.  1.  1.  1.  1.  1.  1.  0.  1.  1.  1.  0.  0.  1.
  1.  1.  1.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  0.  1.  0.  1.  0.
  1.  0.  1.  1.  1.  0.  1.  1.  0.  0.  0.  0.  1.  1.  0.  1.  0.  0.
  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.]
[ 0.  1.  1.  0.  1.  1.  1.  1.  1.  0.  0.  0.  1.  1.  1.  1.  1.  0.
  1.  1.  1.  1.  0.  1.  0.  1.  1.  0.  1.  0.  0.  1.  0.  0.  0.  1.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.
  0.  1.  0.  1.  1.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.
  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.
  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  0.  1.  1.  1.  0.  0.  0.  1.
  1.  0.  1.  1.  1.  0.  0.  0.  1.  0.  1.  0.  0.  1.  1.  1.  1.  0.
  0.  1.  0.  1.  0.  0.  1.  0.  0.  0.

In [26]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,Final_predictions))

ValueError: Can't handle mix of multilabel-indicator and multiclass-multioutput

In [ ]:
Final_predictions